BEGIN(sio_subtest)
	FIELD_8(nothing)
END()

BEGIN(sio_test)
	FIELD_8(f8)
	FIELD_16(f16)
	FIELD_STRUCT(fs, sio_subtest)
	FIELD_ARR_8(farr8, 8)
	FIELD_DYN_8(fdyn8, get_dyn8_size)
	FIELD_DYN_STRUCT(fdyns, sio_subtest, get_dyns_size)
END()
